# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: a4fe6df9ea46fa98e8def73a4e1520a684bd75f91104535edc6052539cdf4bcdd7553af306129958b931b42f498f3c00a01dbbcd32a72be0c633ca542296cd64

test:
  secret_key_base: ac58c876f544f65cdd6f821c41301113656f0da443afdbe8b6d79ece1c8cdddd04126770bb14f79b20396149928b2e79f018bdec2f283f828f0391e71c82828b

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
